#!/bin/bash

echo "Installing Linux dotfiles"
sudo apt update

# Install curl
sudo apt -y install curl
sudo apt -y install tmux
sudo apt -y install curl 
sudo apt -y install git
sudo apt -y install neovim
sudo apt -y install ripgrep
sudo apt -y install fd-find
sudo apt -y install fzf
sudo apt -y install npm
sudo apt -y install nodejs
sudo apt -y install golang-go
sudo apt -y install zsh
sudo apt -y install cmake-curses-gui
sudo apt -y install python3-pip

pip install python-lsp-server

# rust
curl https://sh.rustup.rs -sSf | sh
 
chsh -s $(which zsh) # set zsh to default
 
echo 'Install oh-my-zsh'
sudo rm -r ~/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
 
# powerlevel 10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
# syntax highlight
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
 
rm -f $HOME/.zshrc
rm -f $HOME/.tmux.conf
rm -f $HOME/.gitconfig
rm -f $HOME/.p10k.zsh
rm -rf $HOME/.config/nvim
rm -rf $HOME/.scripts
 
DOT_DIR=$(pwd)

cp $DOT_DIR/zshrc $HOME/.zshrc
cp $DOT_DIR/tmux.conf $HOME/.tmux.conf
cp $DOT_DIR/gitconfig $HOME/.gitconfig
cp $DOT_DIR/p10k.zsh $HOME/.p10k.zsh

mkdir -p ~/.config
cp -r $DOT_DIR/config/nvim $HOME/.config/nvim
mkdir -p ~/.scripts
cp -r $DOT_DIR/scripts/* $HOME/.scripts

exec zsh
